### ISSUE TITLE
zipfile2 is not compatible with Python 2.7.0 to Python 2.7.3

### ISSUE THREAD

**Issue by sjagoe** [cournape/zipfile2#8]
The `zipfile.ZipFile` class became a new-style class in Python 2.7.4. As a result, using zipfile2 in any Python 2.7 version from 2.7.0 to 2.7.3 results in this error on construction:

```python
Traceback (most recent call last):
  File "<module>", line 1
    z = ZipFile('target.zip') as zp:
  File "/home/vagrant/workspace/zipfile2/_zipfile.py", line 57, in __init__
    super(ZipFile, self).__init__(file, mode, compression, allowZip64)
TypeError: must be type, not classobj
```

**Comment by sjagoe** [comment]
https://github.com/cournape/zipfile2/blob/master/zipfile2/_zipfile.py#L21

`IS_BELOW_PY27 = sys.version_info[:2] < (2, 7)` should be:
`IS_BELOW_PY27 = sys.version_info[:2] < (2, 7, 4)`
